urls.py
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^comment/(?P<pk>\d+)/delete$', views.DeleteComment, name='comment.delete'),
    url(r'^amp/(?P<slug>[-\w\d]+)$', views.Amp, name='show'),
    url(r'^(?P<slug>[-\w\d]+)$', views.Show, name='show'),
    url(r'^(?P<slug>[-\w\d]+)/comment$', views.PostComment, name='comment'),
    url(r'^label/(?P<name>\w+)$', views.Label, name='labels'),
    url(r'^admin/(?P<slug>[-\w\d]+)/edit$', views.Edit, name='edit'),
    url(r'^admin/create$', views.Create, name='create'),
    url(r'^admin/(?P<slug>[-\w\d]+)/delete$', views.Delete, name='delete'),
]

templates/blog/admin/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>New Article</h1>
        </div>
        <div class="panel-body">
            <form action="{% url 'blog:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% if errors %}
                    <div class="alert alert-danger">{{ errors }}</div>
                {% endif %}

                {% for field in blog_form %}
                     <div class="form-group">
                        <label class="control-label col-md-2">{{  field.label }}</label>
                        <div class="col-md-10">
                            {{  field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-md-3 col-md-offset-3">
                            <a href="{% url 'blog:index' %}" class="btn btn-block btn-default">Cancel</a>
                        </div>
                    <div class="col-md-3 text-center">
                        <button type="submit" name="update" class="btn btn-primary btn-block">Save Article</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/admin/delete.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block body %}
    {% if blog %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Edit : {{ blog }}</h1>
            </div>
            <div class="panel-body">
                <form action="{% url 'blog:delete' blog.slug %}" method="POST">
                    {% csrf_token %}
                    <p>Are you sure you want to delete this article : {{ blog.title }} ?</p>

                    <div class="form-group">
                        <div class="col-md-3 col-md-offset-3">
                            <a href="{% url 'blog:show' blog.slug %}" class="btn btn-primary btn-block">Cancel</a>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" name="update" class="btn btn-danger btn-block">Delete Article</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/blog/admin/edit.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block body %}
    {% if blog %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Edit : {{ blog }}</h1>
            </div>
            <div class="panel-body">
                <form action="{% url 'blog:edit' blog.slug %}" method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if errors %}
                        <div class="alert alert-danger">{{ errors }}</div>
                    {% endif %}
                    {% for field in blog_form %}
                         <div class="form-group">
                            <label class="control-label col-md-2">{{  field.label }}</label>
                            <div class="col-md-10">
                                {{  field }}
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-md-3 col-md-offset-3">
                            <a href="{% url 'blog:show' blog.slug %}" class="btn btn-block btn-default">Cancel</a>
                        </div>
                        <div class="col-md-3 text-center">
                            <button type="submit" name="update" class="btn btn-primary btn-block">Update Article</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}