urls.py
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^comment/(?P<pk>\d+)/delete$', views.DeleteComment, name='comment.delete'),
    url(r'^amp/(?P<slug>[-\w\d]+)$', views.Amp, name='show'),
    url(r'^(?P<slug>[-\w\d]+)$', views.Show, name='show'),
    url(r'^(?P<slug>[-\w\d]+)/comment$', views.PostComment, name='comment'),
    url(r'^label/(?P<name>\w+)$', views.Label, name='labels'),
    url(r'^admin/(?P<slug>[-\w\d]+)/edit$', views.Edit, name='edit'),
    url(r'^admin/create$', views.Create, name='create'),
    url(r'^admin/(?P<slug>[-\w\d]+)/delete$', views.Delete, name='delete'),
]

templates/blog/partials/_archives.html
{% load i18n %}

<div class="panel panel-info">
    <div class="panel-heading">
        {% trans "Archives" %}
    </div>
    <div class="panel-body">
        <ul class="list-group">

            {% for year, month_dict in archives.items %}
                <li class="list-group-item"><a href="#c{{ year }}" data-toggle="collapse">{{ year }}</a>
                    <div class="panel-collapse collapse" id="c{{ year }}">
                        <ul class="smallindent">
                            {% for month, post_list in month_dict.items  %}
                                <li class="small"><a href="#c{{ year }}m{{month|date:'Y-m-d'}}" data-toggle="collapse">{{ month|date:'F' }}</a>
                                <div class="panel-collapse collapse" id="c{{year}}m{{month|date:'Y-m-d'}}">
                                    <ul class="smallindent">
                                        {% for post in post_list %}
                                            <li class="smalltext"><a href="{% url 'blog:show' post.1 %}">{{ post.2 }}</a>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
            {% endfor %}
	    </ul>
    </div>
</div>

templates/blog/partials/archives.html
<div class="panel panel-info">
    <div class="panel-heading">
        <p class="small">{% trans "Archives" %}</p>
    </div>
    <div class="panel-body">

    </div>
</div>

templates/blog/partials/comment.html
{% load i18n %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{  comment.author.first_name }} {{  comment.author.last_name }}
        <br>{{ comment.created_at }}
    </div>
    <div class="panel-body">
        <p>{{  comment.body|safe }}</p>
    </div>
    <div class="panel-footer">
    {% if user.is_authenticated %}
        <button class="btn btn-default btn-sm reply-button" data-val="{{  comment.pk }}">{% trans "Reply" %}</button>
        {% if user.pk == comment.author.pk %}
            <a href="{% url 'blog:comment.delete' comment.pk %}" class="btn btn-warning btn-sm">{% trans "Delete" %}</a>
        {% endif %}
    {% endif %}
    </div>
</div>

<div class="panel panel-default" id="comment_{{ comment.pk }}_reply" style="display:none;">
    <div class="panel-body">
        <form action="{% url 'blog:comment' blog.slug %}" method="POST">
            <input type="hidden" name="parent_id" value="{{  comment.pk }}">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <textarea class="form-control" name="body"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary btn-sm">[% trans "Post Reply" %}</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% if comment.children %}
    {% for reply in comment.children %}
        <div class="row">
            <div class="col-md-11 col-md-offset-1">
                {% include 'blog/partials/comment.html' with comment=reply %}
            </div>
        </div>

    {% endfor %}
{% endif %}

templates/blog/partials/comment_form.html
{% load i18n %}
{% if user.is_authenticated %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="{% url 'blog:comment' blog.slug %}" method="POST">
                {% csrf_token %}
                {%  for field in comment_form.visible_fields %}
                    {{  field }}
                {% endfor %}
                <p><button type="submit" class="btn btn-primary" id="submit">{% trans "Post Comment" %}</button></p>
            </form>
        </div>
    </div>
{% endif %}

templates/blog/partials/labels.html
{% load i18n %}

{% if blog.tags %}
    <p class="small">{% trans "Labels" %}:
    {% for tag in blog.tags.all %}
        <a href="{% url 'blog:labels' tag.name %}">{{ tag.name }}</a>
        {% if not forloop.last %},{% endif %}
    {% endfor %}
    </p>
{% endif %}